name: Project Validator
on:
  repository_dispatch:
    types: [submit-validation]

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Student Code
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.client_payload.repo }}
      
      - name: Structure Check
        run: |
          if [ ! -f "index.html" ]; then
            echo "Error: Missing index.html"
            exit 1
          fi
          echo "Validation Passed!"
